apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: govana-require-dropped-capabilities
  annotations:
    policies.kyverno.io/title: Require dropped capabilities
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: drop-all-capabilities
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "All Linux capabilities must be dropped."
        foreach:
          - list: "request.object.spec.containers[]"
            pattern:
              securityContext:
                capabilities:
                  drop:
                    - ALL
          - list: "request.object.spec.initContainers[]"
            pattern:
              securityContext:
                capabilities:
                  drop:
                    - ALL
